/*
 * HeaderInclusions.H
 *
 *  Created on: 12-Sep-2014
 *      Author: Nishant Pattanaik
 */

#ifndef HEADERINCLUSIONS_H_
#define HEADERINCLUSIONS_H_

#include <queue>
//#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <netdb.h>
#include <arpa/inet.h>
#include <sys/wait.h>
#include <signal.h>


#endif /* HEADERINCLUSIONS_H_ */
